# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9.xci
# IP: The module: 'design_1_axi_gpio_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9.xci
# IP: The module: 'design_1_axi_gpio_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Universidade/cr/tp6/tp6.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_9/design_1_axi_gpio_0_9.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
