webtalk_init -webtalk_dir D:\\Universidade\\cr\\SHA2\\SHA2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-05-17 18:54:37" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ubca8a6kl00bif3rt4b1ps9r1t" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2395 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.470 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1526575416102" -context "sdk\\\\bsp/1526575416102"
webtalk_add_data -client sdk -key hwid -value "1526071680008" -context "sdk\\\\bsp/1526575416102"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1526575416102"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1526575416102"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1526575416102"
webtalk_add_data -client sdk -key uid -value "1526575428795" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key hwid -value "1526071680008" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key bspid -value "1526575416102" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key projSize -value "86.30859375" -context "sdk\\\\application/1526575428795"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key DebugCount -value "16" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key PerfCount -value "1" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1526579677084"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1526579677084"
webtalk_transmit -clientid 203091273 -regid "" -xml D:\\Universidade\\cr\\SHA2\\SHA2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Universidade\\cr\\SHA2\\SHA2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Universidade\\cr\\SHA2\\SHA2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
